# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Web and API Automation workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.6.1

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # execute gradlew command for running API cucumber test
    - name: Execute Test
      run: ./gradlew apiTests

    # execute gradlew command for running Web UI cucumber test
    - name: Execute Test
      run: ./gradlew webTests

    # archive test result
    - name: Archive Test Result
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: Cucumber Report
        path: target/cucumber-reports.html

    # deploy to GitHub Pages
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports
